import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const vazir = localFont({
  src: '/public/fonts/vazir/Vazir-Medium-FD-WOL.woff2',
  display: 'swap',
  style: 'normal',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazir.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
