import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbar";

const vazir = localFont({
  src: '../../public/fonts/vazir/Vazir-Medium-FD-WOL.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazir.className} antialiased`}
      >
        <Navbar />
        <main className="overflow-x-hidden w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
